### ISSUE TITLE
Virtual Property to ServerDetector and AbstractDrone

### ISSUE THREAD

**Issue by justincdavis** [AutonoLab/pteranodon#106]
AbstractDrone should have a property that is a boolean for is virtual or not. To be used for final implementations.

This could come from ServerDetector if auto or by finding if TCP or UDP address was used.

**Comment by carlsondev** [comment]
Can you elaborate on what "is virtual" is specifically? Is it just if the server is over serial or over IP?

**Comment by justincdavis** [comment]
Yes essentially a flag for over serial or over IP

Can rename to some .serial or .is_serial() thing
